<?php 
/*
Plugin Name: Plugin WP24Horas
Plugin URI: http://thiagoandrade.me/plugins
Description: Descricao do Plugin WP24Horas
Version: 0.0.1
Author: Thiago Andrade
Author URI: http://thiagoandrade.me/
Text Domain: pw
Generated By: http://ensuredomains.com
*/

// If this file is called directly, abort. //
if ( ! defined( 'WPINC' ) ) {die;} // end if

// Let's Initialize Everything
if ( file_exists( plugin_dir_path( __FILE__ ) . 'core-init.php' ) ) {
require_once( plugin_dir_path( __FILE__ ) . 'core-init.php' );
}